In [14]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [15]:
results = pd.read_csv('all_profiles.csv')

In [16]:
results

,sample_id,t,average_battery_percentage,total_current_power_demand,total_VTG_capacity,mean_charging,VTG_percentage,p_smart,pref_home
0,1000,0,99.822237,3452.774031,2323.444713,0.002138,0.0,0.0,0.0
1,1000,1,99.839348,3130.755276,2064.807942,0.001937,0.0,0.0,0.0
2,1000,2,99.855775,2829.982480,1940.124794,0.001741,0.0,0.0,0.0
3,1000,3,99.870442,2554.047457,1668.001063,0.001609,0.0,0.0,0.0
4,1000,4,99.882564,2240.156756,1550.978831,0.001431,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
325727,3160,668,87.597682,204.203067,439.974998,0.000126,1.0,1.0,1.0
325728,3160,669,87.580913,107.640566,278.229803,0.000075,1.0,1.0,1.0
325729,3160,670,87.565616,24.696382,104.623659,0.000023,1.0,1.0,1.0
325730,3160,671,87.552890,94.965294,178.113119,0.000052,1.0,1.0,1.0
325731,3160,672,87.541725,52.865281,118.384556,0.000029,1.0,1.0,1.0